name: Run Jest Tests

on: push
    
jobs:
  jest-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
            node-version: '14'
    - name: Install npm dependencies
      run: npm i

    - name: Run Jest Test
      env:
        UPLOAD_URL: ${{ secrets.UPLOAD_URL}}  
      run: npx jest upload.spec.ts